name: Main

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  LLVM_VERSION: 16

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install APT dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake

      - name: Install LLVM/Clang
        run: |
          sudo apt install lsb-release wget software-properties-common gnupg
          curl -sSf https://apt.llvm.org/llvm.sh | sudo bash -s -- $LLVM_VERSION all

      - name: Configure and build (g++)
        run: |
          cmake $GITHUB_WORKSPACE -B $GITHUB_WORKSPACE/build -DCMAKE_CXX_COMPILER=g++
          cmake --build $GITHUB_WORKSPACE/build
          rm -rf $GITHUB_WORKSPACE/build

      - name: Configure and build (clang++)
        run: |
          cmake $GITHUB_WORKSPACE -B $GITHUB_WORKSPACE/build -DCMAKE_CXX_COMPILER=clang++-$LLVM_VERSION
          cmake --build $GITHUB_WORKSPACE/build
          rm -rf $GITHUB_WORKSPACE/build

      - name: Check clang-format
        run: |
          find src -name '*.cpp' | xargs clang-format-$LLVM_VERSION --dry-run --Werror
          find include -name '*.h' -o -name '*.hpp' | xargs clang-format-$LLVM_VERSION --dry-run --Werror

  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configure CMake
        run: cmake $GITHUB_WORKSPACE -B $GITHUB_WORKSPACE/build

      - name: Build
        run: cmake --build $GITHUB_WORKSPACE/build
